- name: install docker
  become: yes
  apt:
    name: ['docker']
    state:  latest
    update_cache: yes

- name: add couchdb key
  become: yes
  shell: |
    curl -L https://couchdb.apache.org/repo/bintray-pubkey.asc | sudo apt-key add -

- name: add couchdb repository
  become: yes
  shell: |
    echo "deb https://apache.bintray.com/couchdb-deb bionic main" | sudo tee -a /etc/apt/sources.list

- name: install node.js
  become: yes
  apt:
    name: ['nodejs']
    state:  latest
    update_cache: yes

- name: install pip
  become: yes
  apt:
    name: ['python3-pip']
    state: latest
    update_cache: yes
  when: ansible_distribution == "Ubuntu"

- name: Update pip
  become: yes
  pip:
    name: ['pip']
    state: latest
    executable: pip3

- name: Install Tweepy
  become: yes
  pip:
    name: ['tweepy']
    state: latest
    executable: pip3

- name: Install openstack
  become: yes
  pip:
    name: ['openstacksdk']
    state: latest
    executable: pip3

- name: Install numpy
  become: yes
  pip:
    name: ['numpy']
    state: latest
    executable: pip3

- name: Install textblob
  become: yes
  pip:
    name: ['textblob']
    state: latest
    executable: pip3


- name: change script permissions
  become: yes
  shell: |
    sudo chmod 777 /home/ubuntu/CCCgrp20/prechanges.sh
- name: change script permissions
  become: yes
  shell: |
    sudo chmod 777 /home/ubuntu/CCCgrp20/install_couchdb.sh


- name: install couchdb
  become: yes
  command: sh /home/ubuntu/CCCgrp20/prechanges.sh
- name: install couchdb
  become: yes
  command: sh /home/ubuntu/CCCgrp20/install_couchdb.sh "172.26.132.134"